server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
      
      
zuul:
  routes:
    customer:
      serviceId: CustomersService
    product:
      serviceId: ProductsService
    cart:
      serviceId: ShoppingService
    order:
      serviceId: OrderService
      
spring:
  zipkin: 
    base-url: http://localhost:9411/

sleuth:
    sampler: 
      probability: 1 #100% (default = 10%)
      

      