library(tm)	
library(wordcloud)
library(RColorBrewer)

articleCorpus <- readLines("karma.txt")
mycorpus = Corpus(VectorSource(articleCorpus))
# Transformation
mycorpus1 = tm_map(mycorpus,  removePunctuation)
mycorpus2 = tm_map(mycorpus1, removeWords, stopwords("english"))
mycorpus3 = tm_map(mycorpus2, tolower)
mycorpus4 = tm_map(mycorpus3, stripWhitespace)
mycorpus5 = tm_map(mycorpus4, PlainTextDocument)
mycorpus5 = tm_map(mycorpus5, removeWords, c("the","of","which","but","without","every","like","among","let","can","called","just"))
tdm <- TermDocumentMatrix(mycorpus5)
m1 <- as.matrix(tdm)
v1<- sort(rowSums(m1), decreasing=TRUE)
d1 <- data.frame(word=names(v1), freq=v1)
d1 <- head(d1,50)
wordcloud(d1$word,d1$freq,col=brewer.pal(8,"Set2"), min.freq="5",random.order=FALSE)
