//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Feature
{
	public virtual int estimatedWork
	{
		get;
		set;
	}

	public virtual int remainingWork
	{
		get;
		set;
	}

	public virtual int completedWork
	{
		get;
		set;
	}

	public virtual Developer Developer
	{
		get;
		set;
	}

	public virtual Sprint Sprint
	{
		get;
		set;
	}

	public virtual IEnumerable<Project> Project
	{
		get;
		set;
	}

}

